name: Deploy Obsidian Vault via Quartz

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout Quartz v4
        uses: actions/checkout@v4
        with:
          repository: jackyzha0/quartz
          ref: v4
          path: quartz

      - name: Install Quartz dependencies
        working-directory: quartz
        run: npm install

      - name: Remove DND/Sessies folder
        run: rm -rf "./DND/Sessies"

      - name: Copy vault contents into Quartz
        run: |
          rm -rf quartz/content
          mkdir -p quartz/content
          rsync -a DND/ quartz/content/

      - name: Build the site with Quartz
        working-directory: quartz
        run: npx quartz build --directory content

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: quartz/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
