name: Deploy Obsidian Vault via Quartz

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout Quartz v4
        uses: actions/checkout@v4
        with:
          repository: jackyzha0/quartz
          ref: v4
          path: quartz

      - name: Remove unwanted folder from vault
        run: rm -rf "./DND/Sessies"

      - name: Install Quartz dependencies
        working-directory: quartz
        run: npm install

      - name: Copy your Vault into Quartz content
        run: |
          rm -rf quartz/content
          mkdir -p quartz/content
          cp -R . DONT_COPY_ME # placeholder, see below
          cp -R DND quartz/content

      - name: Build site via Quartz
        working-directory: quartz
        run: npx quartz build --directory=content

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: quartz/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
